name: dinov3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - omegaconf
  - numpy
  - scipy
  - pyyaml
  - pip
  - pip:
    - ftfy # needed for dino.txt
    - iopath
    - opencv-python
    - omegaconf
    - pandas 
    - regex # needed for dino.txt
    - pandas
    - scikit-learn
    - scikit-learn-intelex
    - submitit
    - termcolor
    - torch 
    - torchvision 
    - torchmetrics
    - tqdm
    - transformers>=4.56.0
    
